---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-bar
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jose-10000/01-argocd-Project.git
    targetRevision: HEAD
    path: argocd-project/environments/staging/second-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
