---
apiVersion: v1
kind: Secret
metadata:
  name: 01-argocd-Project-Private
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/jose-10000/01-argocd-Project-Private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    6k6W5gj6lImZ18vgc2vDAAAAFWFyZ29jZEBhbnRvbnB1dHJhLmNvbQ==
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"
