---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/jose-10000/01-argocd-Project.git
    targetRevision: HEAD
    path: my-app
  destination:
    server: https://kubernetes.default.svc

