apiVersion: v1
kind: Service
metadata:
  name: dev-grupo3
  namespace: project
spec:
  selector:
    app: dev-grupo3
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
